version: "3.8"
services:
  media-manager:
    build: https://github.com/MarkouZz68/media-manager-docker.git
    container_name: media-manager
    ports:
      - "3000:3000"
    volumes:
      # Format : "/chemin/sur/ton/LXC:/chemin/dans/le/container"
      - /shared:/data
      - ./config:/app/config # Pour garder tes fichiers cachés après un redémarrage
    environment:
      - TORRENTS_PATH=/data/Torrents
      - SERIES_PATH=/data/Media/Series
      - FILMS_PATH=/data/Media/Films_Test
    restart: unless-stopped
